- .travis.yml
With PRs from forked repositories the release key can't be decrypted
because the secured variables are hidden.
> Move encrypting key to before deploy

- app/src/main/java/com/github/gotify/NotificationSupport.java
- app/src/main/java/com/github/gotify/service/WebSocketService.java
* Fix persistent notification causing vibration and audio alerts (for example when loosing connection to server)
* Allow message notifications to pop up as heads-up notifications
* Add LED light to message notifications
* Prevent duplicate notification sounds from message group notification
* Add message notification accent color (set to colorPrimary)
> Notification improvements for android 8+

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/github/gotify/init/BootCompletedReceiver.java
Start the Gotify WebSocketService on receiving boot completed broadcast if a Gotify user token is saved in the settings.
Let me know if the BootCompletedReceiver should implement any authorization checks like the InitializationActivity does before starting the service.
(Closes: #25)
> Start Gotify WebSocketService on boot completed

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/github/gotify/login/LoginActivity.java
- app/src/main/res/values/strings.xml
> Allow cleartext traffic

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/github/gotify/service/ReconnectListener.java
- app/src/main/java/com/github/gotify/service/WebSocketConnection.java
- app/src/main/java/com/github/gotify/service/WebSocketService.java
- app/src/main/res/values/strings.xml
This fixes #40 
I refactored the reconnect routine to the `WebSocketService` and added a listener for connectivity changes so that:
- gotify would no longer retry when there is no network activity
- gotify would reconnect immediately if there is a network change
> listen for network changes

- app/src/main/java/com/github/gotify/messages/MessagesActivity.java
- app/src/main/java/com/github/gotify/messages/provider/MessageFacade.java
Images didn't load correctly when the following scenario occurred:
* ApplicationHolder#request
* MessagesActivity.SelectApplicationAndUpdateMessages#execute
* MessagesActivity.SelectApplicationAndUpdateMessages#doInBackground
- method returns List\<MessageWithImage>, but images are "null" because
apps aren't loaded yet.
* MessagesActivity#onUpdateApps
- Now apps were loaded and cached.
* MessagesActivity.SelectApplicationAndUpdateMessages#onPostExecute
- receives List\<MessageWithImage> from #doInBackgroud with "null" images
-> Messages with "null" images are rendered in the ListView
@eternal-flame-AD you can review this if you like otherwise I'd just merge it.
> Fix race condition while loading messages

- app/src/main/res/layout/message_item.xml
The title was being cut off as described in issue #37 . This patch reduces the title font size and adds a top margin to the message text.
> Reduced the title font size and added a top margin for the message text

- app/src/main/res/layout/message_item.xml
With the smaller font-size it is not that easy anymore to differentiate between the title and the content. 
[<img src="https://user-images.githubusercontent.com/14895212/53440883-da1b9900-3a05-11e9-99e2-86bc4f94e20a.png" width="300"/>](https://user-images.githubusercontent.com/14895212/53440883-da1b9900-3a05-11e9-99e2-86bc4f94e20a.png)
> Make title bold

- app/build.gradle
- app/src/main/java/com/github/gotify/messages/ListMessageAdapter.java
- app/src/main/res/layout/message_item.xml
> Fix markdown

- app/src/main/java/com/github/gotify/messages/MessagesActivity.java
Based on [this post](https://github.com/JakeWharton/picasso2-okhttp3-downloader/issues/12#issuecomment-229997551), it appears that Picasso assumes a disk-cache is setup when provided with an already built OKHttpClient.
I had noticed the app and message icons would often appear as placeholders and get reloaded... adding a disk cache allows some local copies to be saved.
> Adding a disk-cache for Picasso image requests.

- app/src/main/java/com/github/gotify/login/LoginActivity.java
- app/src/main/res/values/strings.xml
The problem is that HttpUrl.parse parses URLs with trailing whitespace without problems, but during the URL parsing in ClientFactory an exception is thrown in that case.
Other errors when instantiating the API client are now handled as well.
> Fix freeze when login URL has trailing whitespace.

- app/src/main/java/com/github/gotify/messages/ListMessageAdapter.java
- app/src/main/java/com/github/gotify/messages/MessagesActivity.java
- app/src/main/java/com/github/gotify/messages/provider/MessageDeletion.java
- app/src/main/java/com/github/gotify/messages/provider/MessageFacade.java
- app/src/main/java/com/github/gotify/messages/provider/MessageStateHolder.java
- app/src/main/java/com/github/gotify/messages/provider/PositionPair.java
- app/src/main/res/layout/activity_messages.xml
- app/src/main/res/layout/message_item.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
Firstly the ListView is replaced by the more modern RecyclerView. The swiping functionality is implemented and consequently the delete button removed. Lastly, a snackbar is implemented for undoing the last deletion. To achieve that I had to extend the MessageFacade and MessageStateHolder a bit. I hope I covered all cases.
The removal of the delete button is debatable, but I think the UI looks cleaner without it (especially since it is the same element for every list item).
Bonus question: Why are all of the server operations in MessagesActivity wrapped in an AsyncTask if they end up in a Retrofit `enqueue` call anyway? I think `enqueue` can be called from the UI thread.
> Delete messages by swiping and add snackbar for undoing deletion.

- app/src/main/java/com/github/gotify/messages/ListMessageAdapter.java
This is meant to implement #90. I implemented it to be similar to the experience in the webclient.
I also sneaked in a commit that fixes what I think is a typo (context vs. content).
> Switch between precise and relative timestamp by tapping on the time.

- app/src/main/java/com/github/gotify/messages/MessagesActivity.java
`api.deleteClient()` only create a call but doesn't execute it.
Fixes #113
> Delete client on logout

- app/src/main/java/com/github/gotify/service/WebSocketConnection.java
- app/src/main/java/com/github/gotify/service/WebSocketService.java
Documentation for postDelayed:
> Causes the Runnable r to be added to the message queue, to be run
> after the specified amount of time elapses.
> The runnable will be run on the thread to which this handler
> is attached.
> <b>The time-base is {@link android.os.SystemClock#uptimeMillis}.</b>
> Time spent in deep sleep will add an additional delay to execution.
TL;DR: if the CPU is in deep sleep, the postDelayed runnable won't be executed.
> Fix not working scheduled reconnect

- app/src/main/AndroidManifest.xml
- app/src/main/res/xml/network_security_config.xml
Tested on Android 10 with certificates issued by self-hosted [smallstep](https://smallstep.com/certificates/)
> Fix #131 allow app to use user certificates

- app/src/main/java/com/github/gotify/messages/MessagesActivity.java
- app/src/main/java/com/github/gotify/service/MessagingDatabase.kt
- app/src/main/res/menu/messages_action.xml
- app/src/main/res/values/strings.xml
Merge of pull #148 + unregistration during deletion
> Delete + unregister App

- app/src/main/java/com/github/gotify/messages/MessagesActivity.java
- app/src/main/res/menu/messages_action.xml
- app/src/main/res/values/strings.xml
Since this feature can be useful for the main version I'm PR here. It will be used on the unifiedpush branch to unregister app too
If gotify shows all messages, nothing change.
If we select an app, the right corner menu add "Delete this application" option which shows a dialog to acknowledge to delete the application.
If yes is selected it deletes the app and refresh.
else it does nothing
> Feature : Add option to delete application

- app/src/main/java/com/github/gotify/messages/ListMessageAdapter.java
- app/src/main/java/com/github/gotify/messages/MessagesActivity.java
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/root_preferences.xml
I've added a setting to fulfill one of the improvements proposed by @alekna in #145.
The setting allows the user to choose whether the default display mode for dates should be absolute or relative. Note that the toggle between the two modes is still working when the TextView is clicked.
Here is the settings activity:
And here is the main activity:
I've modified the way the precise date is formatted using the `DateFormat` java module.
> Added setting to toggle precise date as default display

- app/src/main/java/com/github/gotify/messages/provider/ApplicationHolder.java
- app/src/main/java/com/github/gotify/sharing/ShareActivity.java
- app/src/main/res/drawable/ic_info.xml
- app/src/main/res/layout/activity_share.xml
- app/src/main/res/values/strings.xml
When entering the "Push message/ShareActivity" page, I wanted to keep the "Push Message"-Button enabled by default and disable it if necessary (no apps available, request for apps failed). Otherwise the button would be rendered in disabled state first and after the successful request it would be rendered again in enabled state (everytime the user wants to send a message the normal way -> IMHO: That's not smooth).
But this means, there's a small risk that the user could hit the button without an app selected, if loading the apps needs too much time. If that really happens, the user will see a toast message.
I also added a kind of info box which informs the user about the fact that he needs to provide at least one application to push a message.
Fixes #179
> Fix #179, don't allow to push messages if no apps available

- app/build.gradle
- app/src/main/java/com/github/gotify/messages/ListMessageAdapter.java
#173 Using strike through plugin of Markwon library.
Fixes #173
> Added markdown strike-through support

- app/src/main/java/com/github/gotify/MarkwonFactory.java
- app/src/main/java/com/github/gotify/messages/Extras.java
- app/src/main/java/com/github/gotify/messages/ListMessageAdapter.java
- app/src/main/java/com/github/gotify/service/WebSocketService.java
As described in #74 markdown messages should also be renderd inside the android notification if possible.
If not at least the markdown "metadata" should be removed.
Rendering the markdown inside the android notification is basically possible, but tricky. This is because the support for spans in the notification is limited. The spans the Markwon lib generates by default are mostly ignored in notifications, so the span factory must be adapted similar to these examples to fit the android standard:
[Markwon Notification Sample](https://github.com/noties/Markwon/blob/2ea148c30a07f91ffa37c0aa36af1cf2670441af/app-sample/src/main/java/io/noties/markwon/app/samples/notification/NotificationSample.java)
[Markwon RemoteView Sample](https://github.com/noties/Markwon/blob/2ea148c30a07f91ffa37c0aa36af1c …
> Markdown support in notification

- app/src/main/java/com/github/gotify/messages/MessagesActivity.java
- app/src/main/java/com/github/gotify/messages/MessagesModel.java
- app/src/main/java/com/github/gotify/messages/MessagesModelFactory.java
- app/src/main/java/com/github/gotify/messages/provider/ApplicationHolder.java
Created a view model for the messages activity. It holds the objects which provide data to the view. The view model is not destroyed and recreated on screen rotation, so it is also used to hold the information about the selected app and therefore fixes #207. As well this should provide a slight performance improvement on screen rotation.
> Bugfix: Loose app filter on screen rotation

- README.md
- app/src/main/java/com/github/gotify/service/WebSocketConnection.java
- app/src/main/java/com/github/gotify/service/WebSocketService.java
- app/src/main/res/values/strings.xml
Implementation of #197 "Less data in notification drawer".
Refactored the texts in the foreground notification. Notification title is no longer the app name, because it is already provided by the system. Instead the messages are split in title and content or title only. Probably the most frequently viewed foreground notifications look like this:
As described in the issue, the domain is no longer displayed and the foreground notifications are less intrusive because either the content is shortend or the content is partially moved to the title.
Also a singular/plural distinction is done: "Trying to reconnect in 1 minute" and "Trying to reconnect in 3 minutes".
> Foreground notification texts

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/kotlin/com/github/gotify/init/InitializationActivity.kt
- app/src/main/res/values/strings.xml
- build.gradle
I have decided to use [QuickPermissions Kotlin](https://github.com/QuickPermissions/QuickPermissions-Kotlin) as it offers a very simple solution for permission handling.
If you say you don't want that additional library we can surely find a solution.
This PR should bring back full functionality to the Kotlin version of the app.
Closes #270
> Fix missing permissions on newer Android versions

- app/build.gradle
- app/src/main/kotlin/com/github/gotify/init/InitializationActivity.kt
- app/src/main/kotlin/com/github/gotify/login/AdvancedDialog.kt
- app/src/main/kotlin/com/github/gotify/login/LoginActivity.kt
- app/src/main/kotlin/com/github/gotify/messages/ListMessageAdapter.kt
- app/src/main/kotlin/com/github/gotify/messages/MessagesActivity.kt
- app/src/main/kotlin/com/github/gotify/settings/SettingsActivity.kt
- app/src/main/res/layout/activity_login.xml
- app/src/main/res/layout/activity_logs.xml
- app/src/main/res/layout/activity_messages.xml
- app/src/main/res/layout/activity_share.xml
- app/src/main/res/layout/advanced_settings_dialog.xml
- app/src/main/res/layout/app_bar_drawer.xml
- app/src/main/res/layout/client_name_dialog.xml
- app/src/main/res/layout/message_item.xml
- app/src/main/res/layout/message_item_compact.xml
- app/src/main/res/layout/nav_header_drawer.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Here's the mentioned design update.
Most of the code changes are class name changes.
Some things to talk about:
1. On the login page I had to change the hint in the URL edittext from the example URL to a title like "Gotify URL".
That's because the hint moves to the top of the EditText if you input something. That would be misleading if there would be that example URL.  
Do you agree or any other idea here? What we could do is combine a hint and an example url, then the so called "helperText" would be located underneath the text field (for reference see the example [HERE](https://m3.material.io/components/text-fields/overview#38269950-ca0b-40b3-a884-64dfac22a1ef) where it says "Supporting text")
2. On the settings page I had to overwrite the list preference method to use the Material You …
> Design Renewal

- app/src/main/kotlin/com/github/gotify/messages/ListMessageAdapter.kt
- app/src/main/kotlin/com/github/gotify/messages/provider/MessageImageCombiner.kt
- app/src/main/kotlin/com/github/gotify/messages/provider/MessageWithImage.kt
I've taken a look at the MessageImageCombiner.  
It seems that the Kotlin conversion brought this bug as it requires a non-null object, but if there is no image there's no image url string.  
That's at least what I think.
The changes are minimal, please check if it works AND especially check if actually including an image in a message still works, I've never used images.
PS: In the ListMessagesAdapter you can see that I skip loading the image if it's null to avoid unnessecary work by picasso. Is that okay?
Closes #274
> Fix MessageImageCombiner error

- app/src/main/kotlin/com/github/gotify/messages/MessagesActivity.kt
- app/src/main/res/layout/nav_header_drawer.xml
- app/src/main/res/values/strings.xml
Updated some properties of the Navigation header to adapt to very long usernames and URLs:
- cut the username prefix of the url (as it's just a duplicate)
- limit max lines of username and url to 2
- adaptive header size to fit multiline views
- updated placeholder text (this time using tools:text, we don't need android:text because we override the text nevertheless in the Activity)
Closes #261
> Simplify Navigation Header

- app/src/main/res/values-notnight/colors.xml
- app/src/main/res/values-v21/styles.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles.xml
As been [mentioned](https://github.com/gotify/android/pull/289?notification_referrer_id=NT_kwDOAbm1UrM2MzE4NDE2NTMyOjI4OTQ3Nzk0#issuecomment-1539456821) here, I have removed the settings for TranslucentStatusBar, and make It as default.
> TranslucentStatusBar by default.

- app/src/main/kotlin/com/github/gotify/init/InitializationActivity.kt
- app/src/main/res/values/strings.xml
I've now started working on it and it seems that it's functional, at least on Android 14.  
Feel free to test it out, before merging I'd like to verify that everything's working fine on Android 13 and below.
Little insight on why it's not working atm: The permission for scheduling exact alarms is not to be handled like other permissions via a normal dialog, rather you have to send an Intent to the settings page, where you can enable the schedule permission for that specific app.
Closes #293
> Fix exact alarm permission on Android 14

- app/src/main/AndroidManifest.xml
- app/src/main/kotlin/com/github/gotify/login/LoginActivity.kt
- app/src/main/kotlin/com/github/gotify/messages/MessagesActivity.kt
- app/src/main/kotlin/com/github/gotify/messages/MessagesModelFactory.kt
- app/src/main/kotlin/com/github/gotify/service/WebSocketConnection.kt
- app/src/main/kotlin/com/github/gotify/service/WebSocketService.kt
- app/src/main/kotlin/com/github/gotify/settings/SettingsActivity.kt
- app/src/main/res/values/strings.xml
Warnings listed in #306 are fixed.  
I've never used a certificate for Gotify, but at least choosing one from your phone and loading / parsing it does work.
Closes #306
> Fix build warnings

- app/build.gradle
- app/src/main/kotlin/com/github/gotify/init/InitializationActivity.kt
I've realized that this line
https://github.com/gotify/android/blob/310b73ac5531f6e4653542b93b66ecaec48598c9/app/src/main/kotlin/com/github/gotify/init/InitializationActivity.kt#L65
is blocking the UI thread until the condition is true. Because permission requests take some seconds the app is blocking for several seconds, even leading to possible app crashes.
The solution is canceling the splashScreen when requesting permissions and showing the previous "splash screen layout".  
Tested on Android 13 (33) and 14 (34).
> Fix blocking permission requests

- app/src/main/AndroidManifest.xml
- app/src/main/kotlin/com/github/gotify/messages/IntentUrlDialogActivity.kt
- app/src/main/kotlin/com/github/gotify/service/WebSocketService.kt
- app/src/main/kotlin/com/github/gotify/settings/SettingsActivity.kt
- app/src/main/res/layout/activity_dialog_intent_url.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/xml/root_preferences.xml
As discussed before here's the implementation using a dialog activity.  
What's missing now is getting the permission. As it's rather optional to use this feature I wonder how we want to inform the user about the missing permission.
Same as with the other permissions right at the launch (InitializationActivity) or via the settings?
Closes #227
> Protection of intentURL attack using interactive dialog confirmation

- app/src/main/kotlin/com/github/gotify/service/WebSocketService.kt
When the refresh button is clicked in the navigation drawer, then startPushService is executed which registers the handler. The WebSocketService itself is reused, thus isn't created again or destroyed. From my tests the callback isn't registered twice after the refresh. Thus, I'd expect the unregister isn't needed at all because android somehow does this automagically.
Fixes #311
> fix: remove probably unnecessary unregister

- app/src/main/res/layout/activity_messages.xml
- app/src/main/res/layout/message_item.xml
- app/src/main/res/layout/message_item_compact.xml
- app/src/main/res/layout/nav_header_drawer.xml
I've noticed a pretty cluttered console output, with the following two logs:
1.
```
Failed to inflate ColorStateList, leaving it to the framework
java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f0400f9 a=-1}, theme={InheritanceMap=[id=0x7f12000dcom.github.gotify.dev:style/AppTheme.NoActionBar, id=0x7f120009com.github.gotify.dev:style/AppTheme, id=0x7f120255com.github.gotify.dev:style/Theme.Material3.DayNight, id=0x7f12024dcom.github.gotify.dev:style/Theme.Material3.Dark, id=0x7f12005fcom.github.gotify.dev:style/Base.Theme.Material3.Dark, id=0x7f1200b6com.github.gotify.dev:style/Base.V24.Theme.Material3.Dark, id=0x7f12008ecom.github.gotify.dev:style/Base.V14.Theme.Material3.Dark, …
```
> Cleanup console output

- app/src/main/kotlin/com/github/gotify/messages/ListMessageAdapter.kt
- app/src/main/kotlin/com/github/gotify/messages/MessagesActivity.kt
- app/src/main/kotlin/com/github/gotify/messages/provider/MessageWithImage.kt
I've replaced the classic `RecyclerView.Adapter` with the `ListAdapter` (https://developer.android.com/reference/androidx/recyclerview/widget/ListAdapter).
It includes `AsyncListDiffer` (https://developer.android.com/reference/androidx/recyclerview/widget/AsyncListDiffer), which uses DiffUtil to calculate differences between the current and a newly submitted list. This gives a good performance boost when updating the list (especially in Gotifys case where mostly single messages are added / removed at a time.
Furthermore it handles animations for added or removed items by itself, no need to handle that from our side anymore.
> Switch to ListAdapter (replacing RecyclerView.Adapter)

- app/src/main/res/layout/activity_login.xml
This fixes the automatic input of username and password.  
Previously my manager did not recognize the username input field and focused only on the url and password fields.
Please check (if you use a password manager) if that works fine for you.
It's the last PR for now :)
> Improve password manager autofill compatibility

- app/src/main/kotlin/com/github/gotify/service/WebSocketService.kt
As discussed in #325
External apps receiving the intent should still work because the intent action for release versions didn't change, only the debug intent action has changed from  
`com.github.gotify.service.WebSocketService.NEW_MESSAGE`
to  
`com.github.gotify.service.WebSocketService.NEW_MESSAGE.DEBUG`
> Separate broadcasts to prevent duplicate messages

- app/src/main/res/layout/message_item.xml
- app/src/main/res/layout/message_item_compact.xml
---
Closes https://github.com/gotify/android/issues/341
> Adopt hyperlink color for non-markdown messages

- app/src/main/kotlin/com/github/gotify/CoilInstance.kt
- app/src/main/kotlin/com/github/gotify/MarkwonFactory.kt
- app/src/main/kotlin/com/github/gotify/Utils.kt
Closes https://github.com/gotify/android/issues/111
I've used an authenticator instead of an interceptor.  
The difference is that an interceptor is used on every single call which is not needed in our case.  
The authenticator only is called when a request throws a 401 so we try again with basic auth.
---
Here's my caddy config to test it (username: gotify, password: test)
```
(require_basic_auth) {
basicauth {
gotify $2a$14$TSKxQgAh8n2GRe5ehrn/Ju0nWZH9tFXnmdyRF2TC6wbeMuHezx.oa       
}
}
my.domain:1234 {
import require_basic_auth
reverse_proxy localhost:8080
tls internal
}
```
> Basic auth support for images

- app/src/main/kotlin/com/github/gotify/messages/MessagesActivity.kt
Fixes #365
I've requested more information in the playstore review to narrow down the problem but I think this should be most of it. We could add a periodic re-render but this would probably be overkill and the onResume rerender is enough.
> fix: update date-times on app resume

- .github/workflows/main.yml
Bumping the actions to much newer versions
> Workflow action version updates

- app/src/main/kotlin/com/github/gotify/service/WebSocketConnection.kt
- app/src/main/kotlin/com/github/gotify/service/WebSocketService.kt
- app/src/main/res/layout/activity_share.xml
> fix: reconnecting with wrong url/credentials in the background after logout
